language: go
go:
  - 1.9
services:
  - docker
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
script:
  - make
  - goveralls -service=travis-ci -ignore="handlers/static.go,handlers/tmpls/tmpls.go"
  - make buildDockerImage 
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push USER/REPO;
deploy:
  provider: bintray
  user: maxibanki
  file: "build/bintray.json"
  key:
    secure: ErqvSFIlL3d9XuMj+T+hO6xZqll8Ubx0DEdHD6NJKi7sH7Be3b3/vUoPdAjdFOP70DhaccbncGCTPZ9hsNKdqYxZmuKx3WWwH4H4U5YdDIViXtH6+B5KdAmvdZIynaj+THQAbVAhr+QyvcqotNySPd3Ac1HCg2YAcUHme6y3FsiRJ79To80JWxTSR1G/oObmeoDn8R18wmH1gHl8KQ7ltC537Osb/H34bJ/hY94hRe8IEmoQE4yz/EP44kGXRb/F87i92y1mO081ZS1I1hs5Kbom43YoItqSVbJP/abPMyCsGDv2FGXaGqk5IVC1k+01pcAjqxCzMvXC272itc0E8OEWqE4qONN+m2S9tyALyOaUZ7j5meWLHQj49Rzo7XIWh1PvvEMovdl/wk/Oc9f0ZywPuvoRht5ZebgXbPWAMMNywwy0GKM4nU0DCyFm23mlzPh4iklo12gEUzq3YLc18RhAZuy4timeevrDCuJMQeQ3sqcQBKCQ+rdOxzVCKKl2sGpNaTJEYaHGT9KLCEGBLmvaB58RKgmGN6IIEwpxSm2SGoirfnQsr+DP+kaSvWPr6R/pZAhO1JzO+azaXvfr+hL2SMX6U7j5+SDmFGIFDwxok7ny1QUTQXKlNzA/ks9/vufe30hrTkph/MfEvM5mYVbfgAn5zZ0v+dJ2wCoe1go=
notifications:
  webhooks:
    - https://ws.b0n.pl/relaunch
env:
  global:
  - secure: "W6rdGN9tavB0DdzWcZ+2oKbodszrpUfodg0rbdRfA97ho3xwrRDtogzascSdu7tGXyN2w39CRtp+yY8i4+BJGqFl58m2qoWKOR/XBeAVzvZ093TQOBEPSOggIPgzpyGF+VgH9MOE4kPUViRKPMM0HGRs7Vq8ts9mGaNO9cX7tNr2QoRUpiHuNLZ18nKn25yZ/8kclL8KDz9UDD/sCCC+PLyvXCJsXEnKaJq/bLAPj/uo3kF5A8SJIN3agOQH/TQObycN4uyvo1XTFTSab0X3S78muEsRAY3zH4fHvEHwzuuCTITEwLna3KbAAKl5HCWP6o32ECLFyTsLWqoiSJjEEkvHS++SpK2JNWxq4K83riDhnzEofpeLlHb9FXXbD59En3Pc2OEAT7Zbf4OSdObF2AA80y28tYUAreo15YD6jNWALcac2x1ZRIKUH1drBByVZaFRpLM2aklPZvDuQXM7T1HmyTwhZzGYue03sg/XUcknmq9AoKukU8DlOxv9fydVzoq4tZhUEbjSii8kuiPU/EffT+hZVe0FyUZtnq7mQxcr+aXUIQqKlWDiUcQUWtb7BpQunqvdMg0lbxdaTFtpn+f8B3tPVAdKrxEsFTlhlYNNEsA4renhbPPLN5Qd0EMFi05Rf4QpLiB76E97m8BB9odaCtwVOoC7XKTX+kG/V40="
  - secure: "hp+ghJqS4+ElM/mk0W/8L9JUoapFttkyhCBaWdwQSthj3pSpc5m54HqxOSIvFQREMUW6x/Q70CLx0IHR8D7EqtlJ/CD4HsiYLVNtB3I+05sXLJ/qLPh3HhJ0X7bLWkb5ti5b4hRSGUgeMRqbJOOS9qcJbUb05+3HxPpK761GYzgUy1zPqsL0BnEkaUVD460H9loK5MfYLJ19M2IfVu0Ls84E3s3dfPgnmxrnjH9jq8c3TyE5sI4QqIRpcwXP2zr3xQNxaYWqXQTqcz1ni5dU7YS4nikHAeu6lAVjAsN5wI5NqZXsSutxvj3BE0nGijaQjGmJBMAsOooNZmJw9ZvK/ohU8o43v4u2HMytrYla5ziRzlXn2dqBRCPu++r1UrMj1AM0d8f8lmO4e4xt5QiVlLdwWag2/uVxg9piChJLpDjBP5MRt7q4vi3S2jG+P6I23loV9e+WUCFykpcEFsfD/T7MyYKDIWDzPrLGSRSBZbl1Czbi6c7myApQGnoW9s/ZVTEzJvInbzv79jefxKCFMkLZkI3vnFXf2Ef/2nSAMGmNpB6ZVmSkXKPWeMWVICakco1/GhWAYxtLsdlW9iYJZrQfOa1vOpBpvh7eoX+rqLtfIrqwrwvH8O8MmXEllz52eXnhjpdDbB9p5usiH+wzrgDCcjAmeE8OPVvkEzh0hEY="
