golang_url_shortener:
  image: maxibanki/golang_url_shortener
  ports:
    - 8080:8080
  volumes:
    - ./data:/data
  environment:
    - GUS_BASE_URL=https://s.b0n.pl
    - GUS_GOOGLE_CLIENTID=
    - GUS_GOOGLE_CLIENTSECRET=
    - GUS_GITHUB_CLIENTID=
    - GUS_GITHUB_CLIENTSECRET=
    - GUS_MICROSOFT_CLIENTID=
    - GUS_MICROSOFT_CLIENTSECRET=
  restart: always
